### ISSUE TITLE
Release 2.13.x scala 3 version

### ISSUE THREAD

**Issue by jtjeferreira** [pjfanning/jackson-module-enumeratum#10]
I [see](https://mvnrepository.com/artifact/com.github.pjfanning/jackson-module-enumeratum) that versions 2.15.x and 2.14.x have scala3 versions, but not 2.13.x. 
Any chance you could make a release of 2.13.x with scala 3?

**Comment by pjfanning** [comment]
I've just published a v2.13.5 release that includes Scala 3 support.

**Comment by jtjeferreira** [comment]
Thanks for the rapid response
